### ISSUE TITLE
REQUIRED process [emsgc_main-2] has died!

### ISSUE THREAD

**Issue by doublemanyu** [HKUST-Aerial-Robotics/EMSGC#3]
"REQUIRED process [emsgc_main-2] has died!"
================================================================================
hi, thanks for your wonderful work.
when I do the last step command "$ roslaunch emsgc box_seq00.launch", I met a error like that:
================================================================================
REQUIRED process [emsgc_main-2] has died!
process has died [pid 6300, exit code -11, cmd /root/catkin_ws/devel/lib/emsgc/emsgc_main /root/catkin_ws/src/EMSGC/calib/EV_IMO /root/catkin_ws/src/EMSGC/cfg/evimo/box/seq00.yaml /root/workspace/dataset/DVS/EMSGC_DATASET/EV-IMO/box/seq00/events.txt /root/catkin_ws/src/EMSGC/result/EV-IMO/box/seq00 __name:=emsgc_main __log:=/root/.ros/log/350e2104-b661-11ec-9183-0242ac120002/emsgc_main-2.log].
log file: /root/.ros/log/350e2104-b661-11ec-9183-0242ac120002/emsgc_main-2*.log
Initiating shutdown!
================================================================================
Did you met this error before? Can you give some advice? Thank you in advance.

**Comment by Ethan-Zhou** [comment]
Have you ever tried other lauch file? I cannot figure out your problem from the given information. Have you put the data into the correct directory?
